# -*- coding: utf-8 -*-
"""Q&A activity student file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jNoi893QjfC5fsMRkTjimSV8m8FpxkFu

## 1. Complete the following code to find the area of an equilateral triangle. Output should be as displayed
"""

import math
side=float(input("Enter the side of the equilateral triangle: "))
area=(math.sqrt(3)/4)*math.pow(side,2)
print('Area=',area)

"""## 2. Write a program to count the number of each characters in a string"""

n=str(input('Enter you string'))
n1=str(n.lower())
x=""
for i in n1:
    if i not in x:
        print(i,"occurs",n1.count(i),"times")
        x=x+i

"""## Write a program to find the area and perimeter of a rectangle using functions"""

def area(a,b):
  return a*b
def perimeter(a,b):
  return 2*(a+b)
l=float(input('Enter the length'))
b=float(input('Enter the breadth'))
print('Area=',area(l,b))
print('Perimeter=',perimeter(l,b))

"""## 4. Write a program to print the fibonacci series till a specified number"""

n=int(input("Enter your limit: "))
a=0
b=1
sum=0
count=1
print("Fibonacci series: ", end=" ")
while (count<=n):
  print(sum,end=" ")
  count+=1
  a=b
  b=sum
  sum=a+b

"""## 5. Complete the following code to find the minimum of 3 number using cinditional statements. Output should be as displayed"""

a,b,c = input("Enter three numbers followed by  : ").split()

print("First number :",a)
print("Second number :",b)
print("Third number :",c)

if(a==b==c):
    print("Entered numbers are equal!!!")
if (a<b) and (a<c):
  print(a," is smallest")
if(b<a) and (b<c):
  print(b," is smallest")
if(c<a) and(c<b):
  print(c," is smallest")

a,b,c = input("Enter three numbers followed by space : ").split()

print("First number :",a)
print("Second number :",b)
print("Third number :",c)

    print("Entered numbers are equal!!!")

    print(a," is smallest")

    print(b," is smallest")

    print(c," is smallest")

"""## 6. Write a program to print star pyramind. The number of rows should be taken as input from the user"""

n=int(input("Enter number of rows: "))
for i in range(0,n):
  for j in range(0,i+1):
    print("* ",end="")
  print("\r")

"""## 7. Complete the following code to convert hour into seconds. Output should be as displayed"""

def to_seconds(t):
  return t*3600
time_in_hours = int(input('Enter time in Hours :'))
print(time_in_hours ," Hour is equal to" ,to_seconds(time_in_hours) ," Seconds")

"""## 8. Write a program to print multiplication table as below"""

def multiply(n):
  for i in range(1,11):
    print(i,'*',n,'=',n*i)
num=int(input('Enter a number to find the multiplication table'))
multiply(num)

"""## 9. Write a program to take your 5 favorite food as list and print each as 'I like Biriyani'"""

a,b,c,d,e=input('Enter your list of favorite food:').split()
print('I like',a)
print('I like',b)
print('I like',c)
print('I like',d)
print('I like',e)

"""## 10. Find error(s) in the following code(if any) and rewrite code.


"""

x= int(input('Enter value for x:'))
y=int(input('Enter a value for y:'))
if(x==y):
  print("They are equal")
else:
  print( "They are unequal")